# Generated by Django 5.0.4 on 2024-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_videomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='hvideo',
            field=models.FileField(upload_to='static/uploads/'),
        ),
    ]
