# Generated by Django 5.0.4 on 2024-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_alter_videomodel_hvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=100)),
                ('dimg', models.FileField(upload_to='static/uploads/')),
                ('ddis', models.TextField()),
            ],
        ),
    ]
