# Generated by Django 5.0.4 on 2024-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_departmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StulifeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stulimg', models.FileField(upload_to='static/uploads/')),
                ('stultitle', models.CharField(max_length=100)),
                ('stuldis', models.TextField()),
            ],
        ),
    ]
