# Generated by Django 5.0.4 on 2024-04-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_stulifemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faciimg', models.FileField(upload_to='static/uploads/')),
                ('facidis', models.TextField()),
            ],
        ),
    ]
