# Generated by Django 5.0.4 on 2024-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_facilitymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus_dis', models.TextField()),
                ('aboutus_img', models.FileField(upload_to='static/uploads/')),
            ],
        ),
    ]
