# Generated by Django 5.0.4 on 2024-05-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_historymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgDirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgdis', models.TextField()),
                ('msgdimg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
    ]
