# Generated by Django 5.0.4 on 2024-05-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0009_msgdirectormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=100)),
                ('lposition', models.CharField(max_length=100)),
                ('limg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
    ]
