# Generated by Django 5.0.4 on 2024-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0010_leadershipmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admininame', models.CharField(max_length=100)),
                ('adminiposition', models.CharField(max_length=100)),
                ('adminiimg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
    ]
