# Generated by Django 5.0.4 on 2024-05-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_facultymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stafname', models.CharField(max_length=100)),
                ('stafdep', models.CharField(max_length=100)),
                ('stafimg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
    ]
