# Generated by Django 5.0.4 on 2024-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_staffmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhystdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whytitle', models.CharField(max_length=100)),
                ('whydis', models.CharField(max_length=400)),
            ],
        ),
    ]
