# Generated by Django 5.0.4 on 2024-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0014_whystdmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrcelldisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grdis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcellfunModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grfun', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrcellobjModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grobj', models.TextField()),
            ],
        ),
    ]
