# Generated by Django 5.0.4 on 2024-05-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0015_grcelldismodel_grcellfunmodel_grcellobjmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntirModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antirdis', models.TextField()),
            ],
        ),
    ]
