# Generated by Django 5.0.4 on 2024-05-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0016_antirmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WocelldisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wodis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WocellfunModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wofun', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WocellobjModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woobj', models.TextField()),
            ],
        ),
    ]
