# Generated by Django 5.0.4 on 2024-05-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0017_wocelldismodel_wocellfunmodel_wocellobjmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqopobjModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqopobj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EqoprolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eqoprol', models.TextField()),
            ],
        ),
    ]
