# Generated by Django 5.0.4 on 2024-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0018_eqopobjmodel_eqoprolmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EleobjModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleobj', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ElerolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elerol', models.TextField()),
            ],
        ),
    ]
