# Generated by Django 5.0.4 on 2024-05-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0020_sexhmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BcsAdpMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcsadp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BcsAdqMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcsadq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BcsCdMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcscd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BcsElgMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcselg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BcsIsMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BcsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcsdis', models.TextField()),
                ('bcsimg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='BcsNriMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcsnri', models.TextField()),
            ],
        ),
    ]
