# Generated by Django 5.0.4 on 2024-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0021_bcsadpmodel_bcsadqmodel_bcscdmodel_bcselgmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaAdpMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baadp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaAdqMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baadq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaCdMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bacd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaElgMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baelg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BaIsMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bais', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BAModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badis', models.TextField()),
                ('baimg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='BaNriMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banri', models.TextField()),
            ],
        ),
    ]
