# Generated by Django 5.0.4 on 2024-05-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0022_baadpmodel_baadqmodel_bacdmodel_baelgmodel_baismodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McsAdpMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcsadp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='McsAdqMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcsadq', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='McsCdMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcscd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='McsElgMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcselg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='McsIsMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='McsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcsdis', models.TextField()),
                ('mcsimg', models.FileField(upload_to='static/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='McsNriMOdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcsnri', models.TextField()),
            ],
        ),
    ]
