# Generated by Django 5.0.4 on 2024-05-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0024_isobjmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NriobjModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nriobj', models.TextField()),
            ],
        ),
    ]
