# Generated by Django 5.0.4 on 2024-05-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0025_nriobjmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AslideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aslide', models.FileField(upload_to='static/uploads/')),
            ],
        ),
    ]
