# Generated by Django 5.0.4 on 2024-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0026_aslidemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobdis', models.CharField(max_length=200)),
                ('jobdate', models.CharField(max_length=50)),
            ],
        ),
    ]
