# Generated by Django 5.0.4 on 2024-05-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0027_jobopmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('ofcontact', models.CharField(max_length=15)),
            ],
        ),
    ]
