# Generated by Django 5.0.4 on 2024-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0028_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsandstoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsimg', models.FileField(upload_to='static/uploads/')),
                ('nsdate', models.CharField(max_length=100)),
                ('nstitle', models.CharField(max_length=100)),
                ('nsdis', models.TextField()),
                ('nors', models.CharField(max_length=10)),
            ],
        ),
    ]
