# Generated by Django 5.0.4 on 2024-05-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0029_newsandstorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventimg', models.FileField(upload_to='static/uploads/')),
                ('eventdate', models.CharField(max_length=100)),
                ('eventtitle', models.CharField(max_length=100)),
                ('eventdis', models.TextField()),
                ('puevent', models.CharField(max_length=10)),
            ],
        ),
    ]
