# Generated by Django 5.0.4 on 2024-05-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0031_gallerymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AaboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutdis', models.TextField()),
            ],
        ),
    ]
