# Generated by Django 5.0.4 on 2024-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0032_aaboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AobjectiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aobjective', models.CharField(max_length=300)),
            ],
        ),
    ]
